Feature/appium mobile
garcanam/ods-quickstarters pull request #4
Opened 2024-12-11 08:44 UTC by garcanam

[TPS2021-517](https://jira.biscrum.com/browse/TPS2021-517) [IPA] Mobile testing enablement

2024-12-11 10:02 UTC, roicarrera requested changes

2024-12-11 10:02 UTC, roicarrera commented on docs/modules/quickstarters/pages/e2e-spock-geb.adoc
incluir en el adoc explicación de saucelabs, para que sirve y breve explicación de como usarlo (definir credenciales, etc)

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/Jenkinsfile
> +def createSauceLabsOpenshiftSecret(def context) {
yo añadiría aqui (y/o en el .adoc) una breve explicación de que hacer con este secret para trabajar con saucelabs, tipo "go to openshift and change the default username and password in the secret"

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/Jenkinsfile.template
> +          stash(name: "installation-test-reports-junit-xml-${context.componentId}-${context.buildNumber}", includes: 'build/test-results/*installation*/*.xml', allowEmpty: true)
algún motivo para el * antes de installation o es un typo? Por qué es distinto del caso no-prod?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/Jenkinsfile.template
> +          error "Executing tests failed!"
si el status es distinto de 0 mejor mandaría unstable (si los tests salen failed la pipeline no debería fallar). En geb+spock hay códigos de error más precisos que podamos usar para saber si el status!=0 es por un fail o un error?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/build.gradle
> +java {
la imagen de jdk ya tiene java 21, por qué no usarlo? Hay incompatibilidad de versiones?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/build.gradle
> +def executeTestProd(def type, def language, def env) {
para que se usa esta función? Es duplicada de executeTest y no veo donde se está usando

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/build.gradle
> +            dependsOn generateTaskName(TestExecutionPhases.INSTALLATION, language, env.value)
este dependsOn no debería ser a executeTest?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoGebHomePageSpec.groovy
> +    def setupSpec() {
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +    def setupSpec() {
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +    @IgnoreIf({ System.getProperty("geb.env") != Environments.MOBILE_APP})
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +            if (!specificElements.isEmpty() && specificElements[0].isDisplayed()) {
no es necesario hacer este check. Si hace un click y el elemento no existe fallará solo, y así el test de ejemplo queda más limpio

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +        } catch (Exception e) {
no tiene sentido hacer un try catch en un test, y menos dentro del when, deja que el test falle normal

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +        assert true
hay algun expect que podamos poner de ejemplo que no sea un assert true?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +    def setupSpec() {
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
no tiene sentido hacer un try catch en un test, y menos dentro del when, deja que el test falle normal. Cuando puede haber un assertion error aqui?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
no tiene sentido hacer un try catch en un test, y menos dentro del then, deja que el test falle normal

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
no tiene sentido hacer un try catch en un test, y menos dentro del when, deja que el test falle normal

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
no tiene sentido hacer un try catch en un test, y menos dentro del then, deja que el test falle normal

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/installation/groovy/DemoInstallationSpec.groovy
> +    def setupSpec() {
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 10:02 UTC, roicarrera commented on e2e-spock-geb/files/src/test/integration/groovy/DemoIntegrationSpec.groovy
> +    def setupSpec() {
hay alguna forma de hacer este skip a más alto nivel? Que no use el spec a no ser que el environment sea el que toca?

2024-12-11 13:11 UTC, garcanam commented on docs/modules/quickstarters/pages/e2e-spock-geb.adoc
done: https://github.com/garcanam/ods-quickstarters/pull/4/commits/c26d514a66feae9b1fbb7ad96d9c3d9ebd0a15f8

2024-12-11 13:17 UTC, garcanam commented on docs/modules/quickstarters/pages/e2e-spock-geb.adoc
https://github.com/garcanam/ods-quickstarters/pull/4/commits/c26d514a66feae9b1fbb7ad96d9c3d9ebd0a15f8

2024-12-11 13:18 UTC, garcanam commented on e2e-spock-geb/Jenkinsfile
> +def createSauceLabsOpenshiftSecret(def context) {
@roicarrera  lo he añadido en el adoc mejor que este jenkins no se yo si lo ve nadie... https://github.com/garcanam/ods-quickstarters/pull/4/commits/ade4de70dc61b13af5be74d84c84235974878a95

2024-12-11 13:21 UTC, garcanam commented on e2e-spock-geb/Jenkinsfile.template
> +          stash(name: "installation-test-reports-junit-xml-${context.componentId}-${context.buildNumber}", includes: 'build/test-results/*installation*/*.xml', allowEmpty: true)
@roicarrera hecho https://github.com/garcanam/ods-quickstarters/pull/4/commits/a62fa41af9eb949edc5bc993cf33ce4f63569c02

2024-12-11 13:50 UTC, garcanam commented on e2e-spock-geb/files/build.gradle
> +java {
solo modificando la version no es suficiente, falla, así que de momento se queda con el 17 :/

2024-12-11 13:50 UTC, garcanam commented on e2e-spock-geb/files/build.gradle
> +def executeTestProd(def type, def language, def env) {
eliminada

2024-12-11 13:51 UTC, garcanam commented on e2e-spock-geb/files/build.gradle
> +            dependsOn generateTaskName(TestExecutionPhases.INSTALLATION, language, env.value)
ya comentado

2024-12-11 13:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoGebHomePageSpec.groovy
> +    def setupSpec() {
he probado lo de los tags pero no le hace caso... he quitado todo esto y lo he comentado

2024-12-11 13:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +    def setupSpec() {
he probado lo de los tags pero no le hace caso... he quitado todo esto y lo he comentado

2024-12-11 14:31 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +            if (!specificElements.isEmpty() && specificElements[0].isDisplayed()) {
eliminado

2024-12-11 14:32 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +        } catch (Exception e) {
lo se pero de momento no  he encontrado otra manera para hacerlo y poder enviar feedback a saucelabs

2024-12-11 14:32 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +        assert true
necesitaría try - catch XD

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
lo se pero de momento no  he encontrado otra manera para hacerlo y poder enviar feedback a saucelabs

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
lo se pero de momento no  he encontrado otra manera para hacerlo y poder enviar feedback a saucelabs

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
lo se pero de momento no  he encontrado otra manera para hacerlo y poder enviar feedback a saucelabs

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
lo se pero de momento no  he encontrado otra manera para hacerlo y poder enviar feedback a saucelabs

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/installation/groovy/DemoInstallationSpec.groovy
> +    def setupSpec() {
he probado lo de los tags pero no le hace caso... he quitado todo esto y lo he comentado

2024-12-11 14:33 UTC, garcanam commented on e2e-spock-geb/files/src/test/integration/groovy/DemoIntegrationSpec.groovy
> +    def setupSpec() {
he probado lo de los tags pero no le hace caso... he quitado todo esto y lo he comentado

2024-12-11 14:40 UTC, garcanam commented on e2e-spock-geb/Jenkinsfile.template
> +          error "Executing tests failed!"
lo comentamos

2024-12-11 16:00 UTC, roicarrera commented on e2e-spock-geb/Jenkinsfile
> +def createSauceLabsOpenshiftSecret(def context) {
al revés, el adoc no lo suelen ver, pero conque esté en algun lado ya va bien

2024-12-12 06:40 UTC, garcanam commented on e2e-spock-geb/Jenkinsfile.template
> +          error "Executing tests failed!"
hecho https://github.com/garcanam/ods-quickstarters/pull/4/commits/978db59defc2a575f185345ef09809cd5cc6e56e

2024-12-12 08:50 UTC, garcanam commented on e2e-spock-geb/files/src/test/integration/groovy/DemoIntegrationSpec.groovy
> +    def setupSpec() {
@roicarrera  he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 08:50 UTC, garcanam commented on e2e-spock-geb/files/src/test/installation/groovy/DemoInstallationSpec.groovy
> +    def setupSpec() {
he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 08:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoGebHomePageSpec.groovy
> +    def setupSpec() {
he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 08:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +    def setupSpec() {
he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 08:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +    @IgnoreIf({ System.getProperty("geb.env") != Environments.MOBILE_APP})
he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 08:51 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +    def setupSpec() {
he implementado lo de los tags: https://github.com/garcanam/ods-quickstarters/pull/4/commits/ca8c90d2048bbf34949d542d5bc0f7bd2342f935

2024-12-12 14:20 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
done

2024-12-12 14:20 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileAppSpec.groovy
> +        } catch (Exception e) {
done

2024-12-12 14:20 UTC, garcanam commented on e2e-spock-geb/files/src/test/acceptance/groovy/specs/DemoMobileGebHomePageSpec.groovy
> +        try {
done

2024-12-13 08:22 UTC, merged